# -*- coding: utf-8 -*-
"""ARIMA Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qhZ1kzTMXOzr185J43n8YODQlz0rAhb
"""

import pandas as pd
!pip install git+https://github.com/RJT1990/pyflux
import pyflux as pf
from datetime import datetime

base_url="https://raw.githubusercontent.com/oreilly-mlsec/book-resources/master/chapter3/datasets/cpu-utilization/";

data_train_a = pd.read_csv(base_url+'cpu-train-a.csv', parse_dates=[0], infer_datetime_format=True)
data_test_a = pd.read_csv(base_url+'cpu-test-a.csv', parse_dates=[0], infer_datetime_format=True)

data_train_a.head()

import matplotlib.pyplot as plt 
plt.figure(figsize=(20,8))
plt.plot(data_train_a['datetime'], data_train_a['cpu'], color='black')
plt.ylabel('CPU %')
plt.title('CPU Utilization')

model_a = pf.ARIMA(data=data_train_a, ar=11, ma=11, integ=0, target='cpu')
x = model_a.fit("M-H")

model_a.plot_fit(figsize=(20,8))

model_a.plot_predict_is(h=60, figsize=(20,8))

model_a.plot_predict(h=60,past_values=100,figsize=(20,8))

data_train_b = pd.read_csv(base_url+'cpu-train-b.csv', parse_dates=[0], infer_datetime_format=True)
data_test_b = pd.read_csv(base_url+'cpu-test-b.csv', parse_dates=[0], infer_datetime_format=True)
plt.figure(figsize=(20,8))
plt.plot(data_train_b['datetime'], data_train_b['cpu'], color='black')
plt.ylabel('CPU %')
plt.title('CPU Utilization')

model_b = pf.ARIMA(data=data_train_b, ar=11, ma=11, integ=0, target='cpu')
x = model_b.fit("M-H")

model_b.plot_predict(h=60,past_values=100,figsize=(20,8))

